# Setting
seed: 1337
save_ckpt_path: checkpoints/autoencoder
save_image_path: assets/images/autoencoder

# Data
image_size: 64
base_data_dir: data/animeface/images

# Training parameters
batch_size: 128
num_workers: 16
num_epochs: 40
learning_rate: 5e-4
weight_decay: 1e-2

# Architecture
latent_channels: 16
block_out_channels:
  - 32
  - 64
  - 128
  - 256
  - 512

# Visualization
image_per_row: 8
