# Output and runtime settings
output_dir: ldm_t2i_output
seed: 1337
mixed_precision: bf16
resume_checkpoint: null
pretrained_model_name_or_path: stabilityai/stable-diffusion-2-base
gradient_accumulation_steps: 1

# Dataset settings
data_dir: null # your data directory
precompute: True
resolution: 256
train_batch_size: 64
valid_batch_size: 256
validation_steps: 2500
checkpointing_steps: 5000
num_workers: 16

# Diffusion process settings
beta_start: 0.00085
beta_end: 0.012
beta_schedule: scaled_linear
prediction_type: epsilon
num_inference_steps: 200

# Optimizer and training schedule
optimizer: adamw
learning_rate: 1e-4
weight_decay: 1e-2
max_train_steps: 500000
num_warmup_steps: 10000
max_grad_norm: 1.0

# Model architecture
sample_size: 32
block_out_channels:
  - 256
  - 512
  - 1024
  - 1024
attention_head_dim:
  - 4
  - 8
  - 16
  - 16
cross_attention_dim: 1024

image_per_row: 8
