# Setting
seed: 1337
save_ckpt_path: checkpoints/wgan
save_image_path: assets/images/wgan

# Data
image_size: 64
base_data_dir: data/animeface/images

# Training parameters
batch_size: 128
num_workers: 16
num_epochs: 100
learning_rate: 1e-4
adam_beta1: 0.0
adam_beta2: 0.9
lambda_gp: 10

# Architecture
latent_channels: 256
block_out_channels:
  - 32
  - 64
  - 128
  - 256
  - 512

# Visualization
image_per_row: 8
