# Setting
seed: 1337
checkpoint_save_dir: ./checkpoints/flowmatch
image_save_dir: ./assets/images/flowmatch

# Data
resolution: 64
num_downsample: 4
base_data_dir: ./data/animeface
normalize: true

# Training parameters
batch_size: 128
num_workers: 16
num_epochs: 100
learning_rate: 0.0005

# Architecture
num_train_timesteps: 1000
hidden_channels: 32
dropout: 0.0

# Visualization
nrow: 8
