# Setting
seed: 1337
checkpoint_save_dir: ./checkpoints/wgan
image_save_dir: ./assets/images/wgan

# Data
resolution: 64
num_downsample: 4
base_data_dir: ./data/animeface
normalize: true

# Training parameters
batch_size: 128
num_workers: 16
num_epochs: 100
learning_rate: 0.0001
adam_beta1: 0.0
adam_beta2: 0.9

# Architecture
latent_channels: 256
hidden_channels: 32

# Visualization
nrow: 8
