# Output and runtime settings
output_dir: ldm_output
seed: 1337
nrow: 6
mixed_precision: bf16
resume: false
pretrained_path: null

# Dataset settings
data_dir: data/animeface_np_32
train_size: 132000
valid_size: 8000
train_batch_size: 128
valid_batch_size: 128
validation_steps: 5000

# Diffusion process settings
beta_start: 0.00155
beta_end: 0.015
beta_schedule: scaled_linear
prediction_type: epsilon
num_inference_steps: 200

# Optimizer and training schedule
optimizer: adamw
learning_rate: 5e-5
weight_decay: 1e-2
max_train_steps: 500000
num_warmup_steps: 10000

# Model architecture
sample_size: 32
block_out_channels:
  - 192
  - 384
  - 384
  - 768
  - 768
down_block_types:
  - AttnDownBlock2D
  - AttnDownBlock2D
  - AttnDownBlock2D
  - AttnDownBlock2D
  - DownBlock2D
up_block_types:
  - UpBlock2D
  - AttnUpBlock2D
  - AttnUpBlock2D
  - AttnUpBlock2D
  - AttnUpBlock2D
num_attention_heads:
  - 8
  - 8
  - 8
  - 8
  - 8
layers_per_block: 2
resnet_time_scale_shift: scale_shift
