# Setting
seed: 1337
checkpoint_save_dir: ./checkpoints/ddpm
image_save_dir: ./assets/images/ddpm

# Data
resolution: 64
num_downsample: 4
base_data_dir: ./data/animeface
normalize: true

# Training parameters
batch_size: 128
num_workers: 16
num_epochs: 100
learning_rate: 0.0005

# Architecture
beta_start: 0.0001
beta_end: 0.02
num_train_timesteps: 1000
prediction_type: epsilon
hidden_channels: 32
dropout: 0.0

# Visualization
nrow: 8
