# Setting
seed: 1337
save_ckpt_path: ./checkpoints/vqvae
save_image_path: ./assets/images/vqvae

# Data
image_size: 64
base_data_dir: ./data/animeface

# Training parameters
batch_size: 128
num_workers: 16
num_epochs: 40
learning_rate: 1e-3
weight_decay: 1e-2
lam: 0.1

# Architecture
latent_channels: 16
block_out_channels:
  - 32
  - 64
  - 128
  - 256
  - 512

# Visualization
image_per_row: 8
