# Setting
seed: 1337
save_ckpt_path: checkpoints/stylegan2
save_image_path: assets/images/stylegan2

# Data
image_size: 64
log_resolution: 6
base_data_dir: data/animeface/images
normalize: true

# Training parameters
batch_size: 128
num_workers: 16
num_epochs: 100
learning_rate: 1e-3
lambda_gp: 10

# Architecture
latent_channels: 512
w_dim: 512
mapping_layers: 8
n_features: 32

# Visualization
image_per_row: 8
