# Setting
seed: 1337
save_ckpt_path: checkpoints/vae
save_image_path: assets/images/vae

# Data
image_size: 64
base_data_dir: data/animeface/images

# Training parameters
batch_size: 128
num_workers: 16
num_epochs: 40
learning_rate: 1e-3
weight_decay: 1e-2
beta: 5.0

# Architecture
sample_size: 4 # image_size // (2 ** num_downsample)
latent_channels: 16
block_out_channels:
  - 32
  - 64
  - 128
  - 256
  - 512

# Visualization
image_per_row: 8
