# Setting
seed: 1337
save_ckpt_path: checkpoints/ddpm
save_image_path: assets/images/ddpm

# Data
image_size: 64
base_data_dir: data/animeface/images

# Training parameters
batch_size: 128
num_workers: 16
num_epochs: 100
learning_rate: 5e-4
weight_decay: 1e-2

# Architecture
beta_start: 0.0001
beta_end: 0.02
num_train_timesteps: 1000
prediction_type: epsilon
block_out_channels:
  - 128
  - 256
  - 512
  - 512

# Visualization
image_per_row: 8
